# Your Name or Company
title: Ken Muyesu

# Description of your website. This is used for social sharing.
description:  A freelance iOS Developer based in Nairobi, Kenya.

# A brief blurb about yourself
content: Interested in working together? Let's have a chat.

# Add your social links
social:
  - platform: github
    url: https://github.com/citixenken
  - platform: linktree
    url: https://linktr.ee/citixenken
  - platform: twitter
    url: https://twitter.com/citixenken
  - platform: linkedin
    url: https://www.linkedin.com/in/ken-muyesu/

# General settings
# url: https://citixenken.github.com
# baseurl: "/" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
